version: '3.8'
services:
  # Nginx
  easy-nginx:
    env_file: .env
    image: nginx:latest
    container_name: easy-nginx
    restart: always
    # network_mode: host模式时可以不用映射端口,一般习惯性的映射端口
    ports:
      - '80:80'
      - '443:334'
    volumes:
      # 挂载单个配置文件到宿主机
      - '${ROOT_VOLUME}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf'
      - '${ROOT_VOLUME}/nginx/conf/conf.d:/etc/nginx/conf.d'
      # 日志
      - '${ROOT_VOLUME}/nginx/log:/var/log/nginx/'
      # Html 页面
      - '${ROOT_VOLUME}/nginx/html:/usr/share/nginx/html'
      # 网站挂载
      - '${ROOT_VOLUME}/nginx/www/wwwroot:/www/wwwroot'
      # SSL 证书挂在
      - '${ROOT_VOLUME}/nginx/www/ssl:/www/ssl'
      # 网站日志记录（非 Nginx 系统日志日志）
      - '${ROOT_VOLUME}/nginx/www/wwwlogs:/www/wwwlogs'
    network_mode: 'host'

  # x-ui 容器服务启动
  easy-xui:
    env_file: .env
    image: enwaiax/x-ui
    container_name: easy-xui
    # 自动启动服务
    restart: unless-stopped
    ports:
      - '${XUI_PORT}:54321'
    volumes:
      # x-ui 配置文件挂载到容器外部 /var/appdata/x-ui/conf/config.json
      - '${ROOT_VOLUME}/x-ui/data:/etc/x-ui/'
      - '${ROOT_VOLUME}/x-ui/cert:/root/cert/'
    network_mode: host


  # 自定义编写 x-ui 容器服务启动（启动后可能需要进入容器docker exce -it custom-xui bash 中执行命令systemctl restart x-ui才能启动，后续再处理此问题）
  custom-xui:
    env_file:
      - .env
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - 'CPU=${CPU_A}'
        - 'VERSION=${XUI_VERSION}'
    image: custom-xui:${XUI_VERSION}
    container_name: custom-xui
    # 处理容器内使用 systemctl 命令的权限问题
    privileged: true
    cap_add:
      - 'SYS_ADMIN'
      - 'SYS_PTRACE'
    security_opt:
      - 'seccomp=unconfined'

    # 自动启动服务
    restart: always
    volumes:
      # x-ui 配置文件挂载到容器外部 /var/appdata/x-ui/conf/config.json
      - '${ROOT_VOLUME}/x-ui/conf/config.json:/usr/local/x-ui/bin/config.json'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'

    # network_mode: host模式时可以不用映射端口,一般习惯性的映射端口
    ports:
      - '${XUI_PORT}:54321'
    network_mode: host


